name: 'quakes_dbt'
version: '1.0.0'
config-version: 2

profile: 'quakes_dbt'

model-paths: ['models']
analysis-paths: ['analysis']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

target-path: 'target'
log-path: 'logs'
packages-install-path: 'dbt_packages'
clean-targets: ['target', 'dbt_packages']

models:
  quakes_dbt:
    +materialized: view
    gold:
      +materialized: table

