quakes_dbt:
  target: dev
  outputs:
    dev:
      type: databricks
      host: "{{ env_var('DBX_HOST') }}"
      http_path: "{{ env_var('DBX_HTTP_PATH') }}"
      catalog: "{{ env_var('DBX_CATALOG') }}"
      schema: "{{ env_var('DBX_SCHEMA') }}"
      auth_type: oauth
      client_id: "{{ env_var('AZURE_CLIENT_ID') }}"
      client_secret: "{{ env_var('AZURE_CLIENT_SECRET') }}"
      token_endpoint: "https://login.microsoftonline.com/{{ env_var('AZURE_TENANT_ID') }}/oauth2/token"
      threads: 4