name: dbt-quakes

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "30 6 * * *"

jobs:
  run-dbt:
    runs-on: ubuntu-latest
    env:
      DBX_HOST: ${{ secrets.DBX_HOST }}
      DBX_HTTP_PATH: ${{ secrets.DBX_HTTP_PATH }}
      DBX_CATALOG: ${{ secrets.DBX_CATALOG }}
      DBX_SCHEMA: ${{ secrets.DBX_SCHEMA }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
      SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-databricks==1.10.* certifi
      - name: dbt debug
        working-directory: quakes_dbt
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<'YAML'
          quakes_dbt:
            target: dev
            outputs:
              dev:
                type: databricks
                host: "${DBX_HOST}"
                http_path: "${DBX_HTTP_PATH}"
                catalog: "${DBX_CATALOG}"
                schema: "${DBX_SCHEMA}"
                auth_type: oauth
                client_id: "${AZURE_CLIENT_ID}"
                client_secret: "${AZURE_CLIENT_SECRET}"
                token_endpoint: "https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/token"
                threads: 4
          YAML
          dbt debug -x
      - name: dbt run
        working-directory: quakes_dbt
        run: dbt run --fail-fast
      - name: dbt test
        working-directory: quakes_dbt
        run: dbt test